import { createSlice } from '@reduxjs/toolkit';

const adminSlice = createSlice({
    name: 'admin',
    initialState: {
        isAuthenticated: true, // Set to false by default
        adminInfo: null, // Store admin details when logged in
    },
    reducers: {
        login: (state, action) => {
            state.isAuthenticated = true;
            state.adminInfo = action.payload; // Assign the admin data received from the action
        },
        logout: (state) => {
            state.isAuthenticated = false;
            state.adminInfo = null; // Clear admin data on logout
        },
        updateAdmin: (state, action) => {
            state.adminInfo = { ...state.adminInfo, ...action.payload }; // Update admin details
        },
        
    },
});

  // Export the actions generated by createSlice
export const { login, logout, updateAdmin } = adminSlice.actions;

// Export the reducer to be used in the store
export default adminSlice.reducer;
  