import { createSlice } from '@reduxjs/toolkit';
const userSlice = createSlice({
    name: 'user',
    initialState: {
      isAuthenticated: true, // Set to true for testing purposes
      userInfo: {
        name: 'John Doe',
        email: "akash@mail.com",
        profilePicture: "https://example.com/profile.jpg",
        bio: "Hello, I'm John Doe!",
        location: "New York, USA",
        phone: "+1234567890",
        

      }, // Store user details when logged in default null
    },
    reducers: {
      login: (state, action) => {
        state.isAuthenticated = true;
        state.userInfo = action.payload; // Assign the user data received from the action
      },
      logout: (state) => {
        state.isAuthenticated = false;
        state.userInfo = null; // Clear user data on logout
      },
      updateUser: (state, action) => {
        state.userInfo = { ...state.userInfo, ...action.payload }; // Update user details
      },
    },
  });

  // Export the actions generated by createSlice
export const { login, logout, updateUser } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
  