import { createSlice } from '@reduxjs/toolkit';
const userSlice = createSlice({
  name: 'user',
  initialState: {
    isAuthenticated: false, // Set to true for testing purposes
    isAuthModalOpen: false,
    userData: null,
  },
  reducers: {
    setIsAuthenticated: (state, action) => {
      state.isAuthenticated = action.payload;
    },
    setIsAuthModalOpen: (state, action) => {
      state.isAuthModalOpen = action.payload;
    },
    setUserData: (state, action) => { 
      state.userData = action.payload; 
    },
  },
});

// Export the actions generated by createSlice
export const { setIsAuthenticated, setIsAuthModalOpen, setUserData } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;
